PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE osusumes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(50) DEFAULT NULL,
  regexp VARCHAR(256) DEFAULT NULL,
  content VARCHAR(256) DEFAULT NULL,
  created_by VARCHAR(256) DEFAULT NULL,
  enable BOOLEAN DEFAULT true
);
COMMIT;
